# Generated by Django 4.2.3 on 2023-07-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hammasi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('color', models.CharField(default='', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motor', models.CharField(max_length=100)),
                ('information', models.TextField()),
            ],
            options={
                'db_table': 'CAR',
            },
        ),
        migrations.CreateModel(
            name='car_shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
                ('address', models.CharField(default='', max_length=70)),
                ('car_name', models.CharField(default='', max_length=70)),
            ],
        ),
    ]
