# Generated by Django 4.2.3 on 2023-07-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hammasi', '0002_car_car_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='page',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
