# Generated by Django 4.2.3 on 2023-07-23 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hammasi', '0004_car_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='page',
        ),
    ]
